version: '3.8'

services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5435:5432"
    networks:
      - elt_networks
    environment:  
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init_sql:/docker-entrypoint-initdb.d
  
  destination_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    networks:
      - elt_networks
    environment:  
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  elt_script:
    build: 
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_networks
    depends_on:
      - source_postgres
      - destination_postgres
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.4.7
    command:
      [
        "run",
        "--profiles-dir",
        "/root",
        "--project-dir",
        "/dbt",
        "--full-refresh"
      ]
    networks:
      - elt_networks
    volumes:
      - ./custom_postgres:/dbt
      - ~/.dbt:/root
    depends_on:
      - elt_script
    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev

networks:
  elt_networks:
    driver: bridge
